import '../models/salon.dart';
import '../models/staff.dart';

/// Serwersiz demo / mock API üçin maglumatlar.
///
/// Maksat: UI-daky ähli “suratlar / hyzmatlar / bronlar” backendsiz işlesin.
/// (ID-ler kesgitli bolmagy üçin şunuň ýaly goýuldy.)
final List<Salon> kMockSalons = [
  Salon(
    id: 1,
    name: 'Indi Salonlary',
    address: 'Aşgabat, merkez',
    category: 'Hair',
    imageKey: 'img1',
    latitude: 37.96,
    longitude: 58.33,
    services: [
      // Saç kesim
      Service(id: 1,  name: 'Aýal saç kesimi',            durationMinutes: 40,  price: 350,  categoryKey: 'haircut'),
      Service(id: 2,  name: 'Erkek saç kesimi',            durationMinutes: 25,  price: 200,  categoryKey: 'haircut'),
      Service(id: 3,  name: 'Çaga saç kesimi',             durationMinutes: 20,  price: 150,  categoryKey: 'haircut'),
      Service(id: 4,  name: 'Gysga saç kesimi (trim)',     durationMinutes: 15,  price: 120,  categoryKey: 'haircut'),
      Service(id: 5,  name: 'Pat / çaý kesim',             durationMinutes: 30,  price: 280,  categoryKey: 'haircut'),
      Service(id: 6,  name: 'Arka we boýun düzediş',       durationMinutes: 15,  price: 100,  categoryKey: 'haircut'),
      // Saç boyamak
      Service(id: 7,  name: 'Doly reňk',                   durationMinutes: 90,  price: 900,  categoryKey: 'color'),
      Service(id: 8,  name: 'Kökleri täzelemek',           durationMinutes: 60,  price: 550,  categoryKey: 'color'),
      Service(id: 9,  name: 'Highlight / balýaj',          durationMinutes: 120, price: 1200, categoryKey: 'color'),
      Service(id: 10, name: 'Ton we glýaz',                durationMinutes: 45,  price: 450,  categoryKey: 'color'),
      Service(id: 11, name: 'Reňk düzediş',               durationMinutes: 150, price: 1800, categoryKey: 'color'),
      Service(id: 12, name: 'Moda / fantasy reňk',        durationMinutes: 120, price: 1500, categoryKey: 'color'),
      // Sakal we erkek
      Service(id: 13, name: 'Sakal düzediş',              durationMinutes: 20,  price: 150,  categoryKey: 'beard'),
      Service(id: 14, name: 'Sakal çyzgy (line-up)',       durationMinutes: 25,  price: 180,  categoryKey: 'beard'),
      Service(id: 15, name: 'Doly sakal çak',             durationMinutes: 35,  price: 250,  categoryKey: 'beard'),
      Service(id: 16, name: 'Ýüz sakalý (dry shave)',     durationMinutes: 30,  price: 220,  categoryKey: 'beard'),
      Service(id: 17, name: 'Erkek saç + sakal kombo',    durationMinutes: 50,  price: 380,  categoryKey: 'beard'),
      // Ustilleme we stil
      Service(id: 18, name: 'Fön we stil',                durationMinutes: 30,  price: 300,  categoryKey: 'styling'),
      Service(id: 19, name: 'Wakil / aýratyn ýagdaý üçin', durationMinutes: 60, price: 700,  categoryKey: 'styling'),
      Service(id: 20, name: 'Saç örüm',                   durationMinutes: 50,  price: 500,  categoryKey: 'styling'),
      Service(id: 21, name: 'Ýygyşyk we öwüşme',         durationMinutes: 45,  price: 420,  categoryKey: 'styling'),
      Service(id: 22, name: 'Proba / synag stil',         durationMinutes: 40,  price: 350,  categoryKey: 'styling'),
      // Bejeriş we täsir
      Service(id: 23, name: 'Çuň bejeriş maskasy',        durationMinutes: 30,  price: 400,  categoryKey: 'treatment'),
      Service(id: 24, name: 'Keratin tekizleme',          durationMinutes: 120, price: 2200, categoryKey: 'treatment'),
      Service(id: 25, name: 'Olaplex / baglanyşyk täsir', durationMinutes: 60,  price: 1100, categoryKey: 'treatment'),
      Service(id: 26, name: 'Nemlilik maskasy',           durationMinutes: 25,  price: 320,  categoryKey: 'treatment'),
      Service(id: 27, name: 'Saç arassalaýyş (detox)',    durationMinutes: 30,  price: 380,  categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 2,
    name: 'Fresha Beauty Studio',
    address: 'Aşgabat, Arkadag ýol',
    category: 'Makeup',
    imageKey: 'img2',
    latitude: 37.98,
    longitude: 58.28,
    services: [
      Service(id: 28, name: 'Manikür',  durationMinutes: 45, price: 550,  categoryKey: 'haircut'),
      Service(id: 29, name: 'Gel lak',  durationMinutes: 60, price: 850,  categoryKey: 'treatment'),
      Service(id: 30, name: 'Make-up',  durationMinutes: 50, price: 1000, categoryKey: 'styling'),
    ],
  ),
  Salon(
    id: 3,
    name: 'Green Nails & Hair',
    address: 'Türkmenabat, şäher',
    category: 'Pedicure',
    imageKey: 'img3',
    latitude: 39.12,
    longitude: 63.57,
    services: [
      Service(id: 31, name: 'Pedikür',  durationMinutes: 40, price: 600, categoryKey: 'treatment'),
      Service(id: 32, name: 'Saç stil', durationMinutes: 35, price: 420, categoryKey: 'styling'),
      Service(id: 33, name: 'Nail art', durationMinutes: 25, price: 300, categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 4,
    name: 'Royal Barber House',
    address: 'Balkan, bazar',
    category: 'Hair',
    imageKey: 'img4',
    latitude: 40.0,
    longitude: 52.0,
    services: [
      Service(id: 34, name: 'Barber kesim',      durationMinutes: 30, price: 380, categoryKey: 'haircut'),
      Service(id: 35, name: 'Saç kesim deluxe',  durationMinutes: 45, price: 520, categoryKey: 'haircut'),
      Service(id: 36, name: 'Sakal bejergi',     durationMinutes: 30, price: 290, categoryKey: 'beard'),
    ],
  ),
  Salon(
    id: 5,
    name: 'Aqua Spa & Beauty',
    address: 'Mary, seýil',
    category: 'Makeup',
    imageKey: 'img5',
    latitude: 37.09,
    longitude: 61.84,
    services: [
      Service(id: 37, name: 'Make-up + saç', durationMinutes: 75, price: 1400, categoryKey: 'styling'),
      Service(id: 38, name: 'Manikür + spa', durationMinutes: 55, price: 980,  categoryKey: 'treatment'),
      Service(id: 39, name: 'Pedikür + spa', durationMinutes: 55, price: 990,  categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 6,
    name: 'The Goodfellas by Gianni',
    address: 'Mitte, Nürnberg',
    category: 'Hair',
    imageKey: 'img1',
    latitude: 37.95,
    longitude: 58.38,
    services: [
      Service(id: 40, name: 'Erkek saç kesimi', durationMinutes: 30, price: 200, categoryKey: 'haircut'),
    ],
  ),
  Salon(
    id: 7,
    name: 'Oasis Studio',
    address: 'Mitte, Nürnberg',
    category: 'Laser',
    imageKey: 'img2',
    latitude: 37.93,
    longitude: 58.35,
    services: [
      Service(id: 41, name: 'Lazer epilýasiýasy', durationMinutes: 60, price: 800, categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 8,
    name: 'VeAn TATTOO Nürnberg',
    address: 'Mitte, Nürnberg',
    category: 'Tattoo',
    imageKey: 'img3',
    latitude: 37.94,
    longitude: 58.37,
    services: [
      Service(id: 42, name: 'Tatuýarowka', durationMinutes: 120, price: 1500, categoryKey: 'styling'),
    ],
  ),
  Salon(
    id: 9,
    name: 'Starshine Beauty & Wellness',
    address: 'Mitte, Nürnberg',
    category: 'Spa',
    imageKey: 'img4',
    latitude: 37.96,
    longitude: 58.39,
    services: [
      Service(id: 43, name: 'Spa we masşaž', durationMinutes: 90, price: 1200, categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 10,
    name: 'Modern Aesthetics Hair',
    address: 'Aşgabat, Parahat 7',
    category: 'Hair',
    imageKey: 'ai_hair',
    latitude: 37.91,
    longitude: 58.38,
    rating: 4.9,
    reviewsCount: 124,
    services: [
      Service(id: 44, name: 'Premium Saç Kesimi', durationMinutes: 45, price: 500, categoryKey: 'haircut'),
    ],
  ),
  Salon(
    id: 11,
    name: 'Serenity Luxury Spa',
    address: 'Awaza, Deňiz ýakasy',
    category: 'Spa',
    imageKey: 'ai_spa',
    latitude: 40.01,
    longitude: 52.98,
    rating: 5.0,
    reviewsCount: 89,
    services: [
      Service(id: 45, name: 'VIP Masşaž', durationMinutes: 120, price: 1500, categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 12,
    name: 'Ink Master Tattoo',
    address: 'Aşgabat, 15-nji tapgyr',
    category: 'Tattoo',
    imageKey: 'ai_tattoo',
    latitude: 37.89,
    longitude: 58.33,
    rating: 4.8,
    reviewsCount: 204,
    services: [
      Service(id: 46, name: 'Uly Tatuýarowka', durationMinutes: 180, price: 2000, categoryKey: 'styling'),
    ],
  ),
  Salon(
    id: 13,
    name: 'Glow Up Clinic',
    address: 'Mary, Garaşsyzlyk köçesi',
    category: 'Laser',
    imageKey: 'ai_clinic',
    latitude: 37.59,
    longitude: 61.83,
    rating: 4.7,
    reviewsCount: 56,
    services: [
      Service(id: 47, name: 'Ýüz arassalaýyş', durationMinutes: 60, price: 600, categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 14,
    name: 'Elite Barber Shop',
    address: 'Aşgabat, Köşi',
    category: 'Hair',
    imageKey: 'ai_hair',
    latitude: 37.93,
    longitude: 58.31,
    rating: 4.6,
    reviewsCount: 312,
    services: [
      Service(id: 48, name: 'Sakal we Saç', durationMinutes: 45, price: 300, categoryKey: 'beard'),
    ],
  ),
  Salon(
    id: 15,
    name: 'Royal Thai Massage',
    address: 'Aşgabat, Berkarar',
    category: 'Spa',
    imageKey: 'ai_spa',
    latitude: 37.92,
    longitude: 58.37,
    rating: 4.9,
    reviewsCount: 450,
    services: [
      Service(id: 49, name: 'Taý Masşažy', durationMinutes: 90, price: 800, categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 16,
    name: 'Black Rose Tattoo',
    address: 'Türkmenabat, Merkez',
    category: 'Tattoo',
    imageKey: 'ai_tattoo',
    latitude: 39.08,
    longitude: 63.56,
    rating: 4.8,
    reviewsCount: 120,
    services: [
      Service(id: 50, name: 'Reňkli Tatuýarowka', durationMinutes: 120, price: 1200, categoryKey: 'styling'),
    ],
  ),
  Salon(
    id: 17,
    name: 'Pure Skin Laser',
    address: 'Balkanabat, 212-nji kwartal',
    category: 'Laser',
    imageKey: 'ai_clinic',
    latitude: 39.51,
    longitude: 54.36,
    rating: 5.0,
    reviewsCount: 77,
    services: [
      Service(id: 51, name: 'Tutuş Beden Lazer', durationMinutes: 120, price: 3500, categoryKey: 'treatment'),
    ],
  ),
  Salon(
    id: 18,
    name: 'Gentleman\'s Lounge',
    address: 'Aşgabat, 10-njy ýyl Abadançylyk',
    category: 'Hair',
    imageKey: 'img4',
    latitude: 37.94,
    longitude: 58.39,
    rating: 4.7,
    reviewsCount: 180,
    services: [
      Service(id: 52, name: 'Premium hyzmat', durationMinutes: 60, price: 400, categoryKey: 'haircut'),
    ],
  ),
  Salon(
    id: 19,
    name: 'Lotus Beauty Studio',
    address: 'Daşoguz, Gurbansoltan Eje',
    category: 'Makeup',
    imageKey: 'img2',
    latitude: 41.83,
    longitude: 59.96,
    rating: 4.9,
    reviewsCount: 215,
    services: [
      Service(id: 53, name: 'Toý Makiyajy', durationMinutes: 90, price: 1500, categoryKey: 'styling'),
    ],
  ),
];

Salon mockSalonById(int id) {
  return kMockSalons.firstWhere((s) => s.id == id, orElse: () => kMockSalons.first);
}

final List<Staff> kMockStaffList = [
  const Staff(
    id: 1,
    salonId: 10,
    salonName: 'Modern Aesthetics Hair',
    salonAddress: 'Aşgabat, Parahat 7',
    name: 'Vanessa Siegel',
    role: 'Top Stylist • Color Expert',
    rating: 5.0,
    reviewsCount: 124,
    imageKey: 'avatar_f1',
    distanceKm: 1.1,
  ),
  const Staff(
    id: 2,
    salonId: 19,
    salonName: 'Lotus Beauty Studio',
    salonAddress: 'Daşoguz, Gurbansoltan Eje',
    name: 'Aýgözel',
    role: 'Makeup Artist • Bridal',
    rating: 4.9,
    reviewsCount: 89,
    imageKey: 'avatar_f2',
    distanceKm: 3.4,
  ),
  const Staff(
    id: 3,
    salonId: 14,
    salonName: 'Elite Barber Shop',
    salonAddress: 'Aşgabat, Köşi',
    name: 'Arslan',
    role: 'Master Barber • Fade Specialist',
    rating: 4.8,
    reviewsCount: 312,
    imageKey: 'avatar_m1',
    distanceKm: 5.8,
  ),
  const Staff(
    id: 4,
    salonId: 12,
    salonName: 'Ink Master Tattoo',
    salonAddress: 'Aşgabat, 15-nji tapgyr',
    name: 'Max',
    role: 'Tattoo Artist • Realism',
    rating: 5.0,
    reviewsCount: 204,
    imageKey: 'avatar_m2',
    distanceKm: 12.0,
  ),
];

